= 99 Problems in Java

image:https://travis-ci.org/Mishco/99-problems.svg?branch=master["Build Status", link="https://travis-ci.org/Mishco/99-problems"]

== Overview

This is an adaptation of the link:https://sites.google.com/site/prologsite/prolog-problems[Ninety-Nine Prolog Problems] written by Werner Hett at the Berne University of Applied Sciences in Berne, Switzerland.

From the original source:

    The purpose of this problem collection is to give you the opportunity to practice your skills in logic programming.
    Your goal should be to find the most elegant solution of the given problems.
    Efficiency is important, but logical clarity is even more crucial.
    Some of the (easy) problems can be trivially solved using built-in predicates.
    However, in these cases, you learn more if you try to find your own solution.

    The problems have different levels of difficulty. Those marked with a single asterisk (*) are easy.
    If you have successfully solved the preceding problems you should be able to solve them within a few (say 15) minutes.
    Problems marked with two asterisks (**) are of intermediate difficulty.
    If you are a skilled Java programmer it shouldn't take you more than 30-90 minutes to solve them.
    Problems marked with three asterisks (***) are more difficult.
    You may need more time (i.e. a few hours or more) to find a good solution.

The main purpose for this repository is to train Java skills and also deepen TDD skills link:https://martinfowler.com/bliki/TestDrivenDevelopment.html[Test Driven Development].

== Technology

* Java 14 (https://adoptopenjdk.net/)
* Maven
* Junit5

== Lists

=== link:/src/main/java/lists/P01.java[P01 - Find the last element of the list]

=== link:/src/main/java/lists/P02.java[P02 - Find the second last element of the list]


