= 99 Problems in Java
:toc:

image:https://travis-ci.org/Mishco/99-problems.svg?branch=master["Build Status", link="https://travis-ci.org/Mishco/99-problems"] image:https://sonarcloud.io/api/project_badges/measure?project=Mishco_99-problems&metric=alert_status[Quality Gate Status, link="https://sonarcloud.io/dashboard?id=Mishco_99-problems"]


== Overview

This is an adaptation of the link:https://sites.google.com/site/prologsite/prolog-problems[Ninety-Nine Prolog Problems] written by Werner Hett at the Berne University of Applied Sciences in Berne, Switzerland.

From the original source:

    The purpose of this problem collection is to give you the opportunity to
    practice your skills in logic programming.
    Your goal should be to find the most elegant solution of the given problems.
    Efficiency is important, but logical clarity is even more crucial.
    Some of the (easy) problems can be trivially solved using built-in predicates.
    However, in these cases, you learn more if you try to find your own solution.

    The problems have different levels of difficulty.
    Those marked with a single asterisk (*) are easy.
    If you have successfully solved the preceding problems you should be able
    to solve them within a few (say 15) minutes.
    Problems marked with two asterisks (**) are of intermediate difficulty.
    If you are a skilled Java programmer it shouldn't take you more
    than 30-90 minutes to solve them.
    Problems marked with three asterisks (***) are more difficult.
    You may need more time (i.e. a few hours or more) to find a good solution.

The main purpose for this repository is to train Java skills and also deepen TDD skills link:https://martinfowler.com/bliki/TestDrivenDevelopment.html[Test Driven Development].

== Technology

* Java 14 (https://adoptopenjdk.net/)
* Maven
* Junit5

== Lists

=== link:/src/main/java/lists/P01.java[P01 - Find the last element of the list]

=== link:/src/main/java/lists/P02.java[P02 - Find the second last element of the list]

=== link:/src/main/java/lists/P03.java[P03 - Find the kth element from the list]

=== P04 - Find the number of elements of a list
=== P05 - Reverse a list
=== P06 - Find out whether a list is a palindrome
=== P07 - Flatten a nested list structure
=== P08 - Eliminate consecutive duplicates of list elements.
=== P09 - Pack consecutive duplicates of list elements into sublists
=== P10 - Run-length encoding of a list.
=== P11 - Modified run-length encoding.
=== P12 - Decode a run-length encoded list.
=== P13 - Run-length encoding of a list (direct solution).
=== P14 - Duplicate the elements of a list.
=== P15 - Duplicate the elements of a list a given number of times.
=== P16 - Drop every N'th element from a list.
=== P17 - Split a list into two parts; the length of the first part is given.
=== P18 - Extract a slice from a list.
=== P19 - Rotate a list N places to the left.
=== P20 - Remove the K'th element from a list.
=== P21 - Insert an element at a given position into a list.
=== P22 - Create a list containing all integers within a given range.
=== P23 - Extract a given number of randomly selected elements from a list.
=== P24 - Lotto: Draw N different random numbers from the set 1..M.
=== P25 - Generate a random permutation of the elements of a list.
=== P26 - Generate the combinations of K distinct objects chosen from the N elements of a list
=== P27 - Group the elements of a set into disjoint subsets.
=== P28 - Sorting a list of lists according to length of sublists

== Arithmetic

=== P29

== Logic and Codes

== Binary Tree

== Multiway Trees

== Graphs

== Miscellaneous




